# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebPM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebPM.Contracts')),
            ],
        ),
        migrations.AddField(
            model_name='contracts',
            name='contractType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebPM.ContractType'),
        ),
    ]
