# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 19:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebPM', '0002_auto_20170119_2128'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContractType',
            new_name='ContractTypes',
        ),
    ]
