# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-21 10:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebPM', '0006_auto_20170121_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contracts',
            name='contractType',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='projectattributes',
            name='attrType',
        ),
        migrations.RemoveField(
            model_name='projectattributes',
            name='stage',
        ),
        migrations.DeleteModel(
            name='Contracts',
        ),
        migrations.DeleteModel(
            name='Payments',
        ),
        migrations.DeleteModel(
            name='ProjectAttributes',
        ),
    ]
