# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-21 10:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebPM', '0007_auto_20170121_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('fullPrice', models.IntegerField()),
                ('startDate', models.DateField()),
                ('contractType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebPM.ContractTypes')),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentDate', models.DateField()),
                ('paymentAmount', models.IntegerField()),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebPM.Contracts')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectAttributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attrValue', models.IntegerField()),
                ('attrType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebPM.AttributeTypes')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebPM.Stages')),
            ],
        ),
    ]
