# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebPM', '0009_auto_20170121_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracts',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='WebPM.Projects'),
            preserve_default=False,
        ),
    ]
