# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-03 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPM', '0013_auto_20170125_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documents/', verbose_name='Document')),
                ('uploadDate', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
