# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-05 21:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebPM', '0014_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documents/agreements', verbose_name='Document')),
                ('uploadDate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Upload',
        ),
        migrations.RenameField(
            model_name='payments',
            old_name='payed',
            new_name='confirmed',
        ),
        migrations.AddField(
            model_name='payments',
            name='confirmedDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='agreements',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebPM.Payments'),
        ),
    ]
