# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-07 20:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebPM', '0016_agreements_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreements',
            name='payment',
        ),
        migrations.AddField(
            model_name='payments',
            name='splitAgreement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WebPM.Agreements'),
        ),
        migrations.AlterField(
            model_name='agreements',
            name='uploadDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
