# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-21 20:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebPM', '0017_auto_20170207_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='cancelAgreement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cancel_agreement', to='WebPM.Agreements'),
        ),
        migrations.AddField(
            model_name='payments',
            name='isCanceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payments',
            name='isPostponed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payments',
            name='postponeAgreement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postptone_agreement', to='WebPM.Agreements'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='splitAgreement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='split_agreement', to='WebPM.Agreements'),
        ),
    ]
