# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-21 20:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebPM', '0018_auto_20170221_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='beforePostponedDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='payments',
            name='canceledDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='postponeAgreement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postpone_agreement', to='WebPM.Agreements'),
        ),
    ]
