# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-23 14:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebPM', '0019_auto_20170221_2348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='isCanceled',
            new_name='canceled',
        ),
        migrations.RenameField(
            model_name='payments',
            old_name='isPostponed',
            new_name='postponed',
        ),
        migrations.RenameField(
            model_name='payments',
            old_name='isSplit',
            new_name='split',
        ),
    ]
