# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-20 18:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebPM', '0022_auto_20170320_2104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'permissions': (('view_projects', "Access to main project's view"),)},
        ),
        migrations.AlterModelOptions(
            name='rightssupport',
            options={'managed': False, 'permissions': (('addNewProject', 'Adding new project'), ('addNewRefValue', 'Adding new reference value'))},
        ),
    ]
