# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-20 19:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebPM', '0023_auto_20170320_2136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'permissions': (('viewProjects', "Access to main project's view"),)},
        ),
    ]
