# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-20 19:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebPM', '0024_auto_20170320_2200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payments',
            options={'permissions': (('confirmPayment', 'Confirm payment'), ('unconfirmPayment', 'Unconfirm payment'), ('postponePayment', 'Postpone payment'), ('splitPayment', 'Split payment'), ('cancelPayment', 'Cancel payment'))},
        ),
    ]
