# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 12:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebPM', '0027_auto_20170413_1657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contracts',
            options={'permissions': (('viewContract', 'Access to contract view'),)},
        ),
    ]
