# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPM', '0028_auto_20170424_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracts',
            name='status',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
