# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-29 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPM', '0029_contracts_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stages',
            name='stageType',
        ),
        migrations.AddField(
            model_name='stages',
            name='actualFinishDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='stages',
            name='actualStartDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='stages',
            name='allowanceDuration',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='stages',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stages',
            name='plannedFinishDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='stages',
            name='plannedStartDate',
            field=models.DateField(null=True),
        ),
        migrations.DeleteModel(
            name='StageTypes',
        ),
    ]
