# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-29 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebPM', '0031_auto_20170429_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='StageTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='StageType',
        ),
        migrations.AlterField(
            model_name='stages',
            name='stageType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebPM.StageTypes'),
        ),
    ]
