# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-29 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPM', '0032_auto_20170429_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='stages',
            name='status',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
